root: true
parser: babel-eslint
extends:
  - eslint:recommended
env:
  browser: true
  node: true
rules:
  # possible errors
  no-console:
    - off
  # variables
  no-unused-vars:
    - off
  # stylistic issues
  comma-dangle:
    - error
    - always-multiline
  indent:
    - error
    - tab
    -
      SwitchCase: 1
  linebreak-style:
    - error
    - unix
  new-parens:
    - error
  no-mixed-spaces-and-tabs:
    - error
  quotes:
    - error
    - single
  semi:
    - error
    - never
