root: true
parser: babel-eslint
extends:
 - eslint:recommended
env:
 browser: true
 node: true
rules:
 no-console:
  - off
 no-unused-vars:
  - off
 comma-dangle:
  - error
  -
    arrays: always-multiline
    exports: always-multiline
    functions: always-multiline
    imports: always-multiline
    objects: always-multiline
 indent:
  - error
  - tab
 new-parens:
  - error
 no-mixed-spaces-and-tabs:
  - error
 quotes:
  - error
  - single
 semi:
  - error
  - never
